### ISSUE TITLE
Property - switching when scrolling the video

### ISSUE THREAD

**Issue by ONLiam** [on-associates/rekreate-webflow-scripts#1]
1. can we get rid of the scrolling of the overlays and just have them fade in and out? they should never scroll together with the page.
2. i’d also want to get rid of the scrolling when transitioning between videos, instead i would prefer to have everything fade to black and then fade the new video in. so basically every transition becomes a fade rather than a scroll – hope that makes sense?
3. the overlays should also happen after each video, currently looks like it’s just applied to the first one?

This feedback was written by @Werther-V (converted to issue by @ONLiam)

**Comment by ONLiam** [comment]
1. If I understand the feedback correctly, this is done.
2. The scrolling is still in place here (as the fade is semi transparent). That said I don't mind the current solution… however the transition to the next property in the navigation should happen sooner. The timing should work in parallel with the timing of the black overlay appearing, rather than waiting for the video of the next property to scroll to the top of the viewport.
3. This looks complete if I understand correctly.

Just No.2 to resolve please @MilanVetnic @kaonkd

**Comment by MilanVetnic** [comment]
The second point was deliberate because we had a problem with a fixed header creating a gap at the top if you tried to scroll around the page using nav links, so we needed to push the scrolling links by 100px down and that has an impact how soon the transition should happen inside the navigation from one property to another, when they get a background color 

Solving this issue: "transition to the next property in the navigation should happen sooner" would open up the original problem creating a gap at the top because of a fixed header
I will try few more approaches to get it switching sooner and in sync with the black overlays

**Comment by lizzie-madebyon** [comment]
@MilanVetnic if this will take a long time then let's drop this one - focus on the other issues first and this one last
